### PR TITLE
Improve download buttons

### PR DESCRIPTION
**Pull request by InfinityGhost**
This change moves all of the context menu onto the main download dialog allowing for quicker access to the osu!Direct shortcut and Bloodcat shortcut.

image

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Hi, thanks for the PR.
I do have to say that the reason I hid the other download options was to minimize visual clutter, also because 99% of the times people download from osu!.
Something about having 4 clickable buttons at the same time screams "bad design" to me...

**Comment by InfinityGhost** [comment]
I think it just adds to better flow because when I had supporter I hated using the actual website, and now with the new website it sometimes just throws you into the forum instead of downloading the beatmap.
Maybe moving the Bloodcat mirror back into the download button because they perform the same type of download would reduce clutter?

**Comment by InfinityGhost** [comment]
I generally just think that too many clicks also leads to bad flow design which still harms the user experience just as bad as a cluttered UI.

**Comment by Tyrrrz** [comment]
I agree with you. But that means we have to find a good middle ground. Maybe there's some UI design pattern we can use here?

**Comment by InfinityGhost** [comment]
I'm not too familiar with UI design patterns, but minimizing the amount of clicks would benefit the flow the most.

**Comment by Tyrrrz** [comment]
Okay so I was thinking a bit and I've come up with some ideas.

# Solution 1

Keep everything as is, add a drop down arrow to the Download button (similar to image below). When the user clicks the dropdown and selects Download via bloodcat, this will become the default option for the next time. This will avoid unecessary clicks in the future if the user always downloads from bloodcat. Is it common that users only *sometimes* download from bloodcat?

image

# Solution 2

Reduce the number of buttons:

- We can remove the globe button (go to beatmap page) and turn the beatmap title into a link instead. Clicking on the beatmap title will take you to the beatmap page.
- We can remove the close button and just rely on close-on-click-away mechanic of the popup. Is it intuitive enough?

After removing those buttons we will probably be able to put the download buttons as you suggested.

**Comment by InfinityGhost** [comment]
As for solution 1, bloodcat is generally only used as a mirror when a certain beatmap had its mp3 muted or removed for copyright reasons because it has the first ranked version of the set. Generally, bloodcat has much slower download speeds anyway, so avoiding downloading repeatedly from bloodcat is probably a good idea. Thats my main issue with sticking to the drop down method.

With solution 2, close on click away was how I naturally thought the windows would disappear on my first time using the new GUI, although it didn't. Adding that would be a good improvement no matter the way we go with this in my opinion. The globe icon confused me at first on what it did, so moving it onto the beatmap name as a hyperlink with that format would make more sense to me.

I'm personally in favor of solution 2 as of now.

**Comment by Tyrrrz** [comment]
Awesome. Would you mind converting your PR to solution 2? I'm going on vacation tomorrow and will be back in around a week so I will be able to review it then.

The close on click away mechanic is enabled on [DialogHost](https://github.com/Tyrrrz/OsuHelper/blob/5b49161a8f210dbbc226a07b66a79cc01bed73e5/OsuHelper/Views/RootView.xaml#L22), I think it's called `CloseOnClickAway` or something similar. For title hyperlink, I would prefer if the text was the same as now but it would get underlined and have a hand cursor when hovered over.

**Comment by InfinityGhost** [comment]
Will handle it ASAP

**Comment by InfinityGhost** [comment]
How's this?
image

**Comment by Tyrrrz** [comment]
Hi again.
Thanks for doing this. I'm back from vacation and will look into this as soon as I can.

**Comment by Tyrrrz** [comment]
🎉

**Pull request merged**
